export const SET_ALARMS = "SET_ALARMS";
export const SET_LOADING_ALARMS = "SET_LOADING_ALARMS";
export const SET_ALARMS_ERROR = "SET_ALARMS_ERROR";

export const GET_ALARMS = "GET_ALARMS";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_EDIT_MDOAL = "OPEN_EDIT_MODAL";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const ACTIVATE_NOTIFICATION = "ACTIVATE_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

//MY ALARM ACTIONS
export const CREATE_ALARM = "CREATE_ALARM";
export const EDIT_ALARM = "EDIT_ALARM";
export const DELETE_ALARM = "DELETE_ALARM";
export const PAUSE_ALARM = "PAUSE_ALARM";

export const UPDATE_ALARMS = "UPDATE_ALARMS";

export const SET_SELECTED_ALARM = "SET_SELECTED_ALARM";