export const SET_ALARMS = "SET_ALARMS";
export const SET_LOADING_ALARMS = "SET_LOADING_ALARMS";
export const SET_ALARMS_ERROR = "SET_ALARMS_ERROR";

export const GET_ALARMS = "GET_ALARMS";

//MY ALARM ACTIONS
export const CREATE_ALARM = "CREATE_ALARM";
export const EDIT_ALARM = "EDIT_ALARM";
export const DELETE_ALARM = "DELETE_ALARM";
export const PAUSE_ALARM = "PAUSE_ALARM";
export const RESUME_ALARM = "RESUME_ALARM";

export const SET_SELECTED_ALARM = "SET_SELECTED_ALARM";
export const SET_ALARM_NAME = "SET_ALARM_NAME";